version: "3.9" #optional since vi.27.0
services:
  web:
    build:
      context:  .
      dockerfile: Dockerfile
    image:  go-app-ms:latest
    ports:
      - "80:80"
    restart:  always
    networks:
      - web

networks:
  web:  